### ISSUE TITLE
Feature: "group" coverage?

### ISSUE THREAD

**Issue by elliot-nelson** [istanbuljs/nyc#1112]
## Summary

It would be nice if `nyc` supported the ability to "group" coverage data like SimpleCov.  Or put a different way, to say that incidental coverage from outside the folder doesn't count.

"Soft" version:
- individual folders (like models, controllers, etc) only count coverage from specs in that folder, ignoring splash coverage from other layers of the application.

"Strict" version:
- every file "foo.js" only counts coverage from running "fooSpec.js".  (Zero splash coverage allowed.)

Is this a potential feature, and what exactly would have to change?

## Workarounds

You can accomplish this today with a custom script or grunt task:

- list all specs
- run `istanbul cover jasmine` for each spec individually 
- write a custom script that loads each coverage output and deletes all entries except the target file
- merge coverage files with nyc and report

Essentially this workaround is what I've seen in projects - but I'd like to see it be part of core OR encapsulated in a plugin of some kind.

**Comment by coreyfarrell** [comment]
The latest version of tap has a feature to support this - https://www.node-tap.org/coverage-map/.  I'm not sure nyc can directly support this.

**Comment by elliot-nelson** [comment]
Thanks for the link!  It looks like that's an alternative to jasmine that has a core goal of separating coverage by file, which is a good option for node-based testing.

One difference between tap and jasmine (or mocha) is the ability to run in the browser with karma or selenium.  Running in browser also makes strategies you'd use in node (like just running a separate process for each test file) a non-starter; it would take forever to setup and teardown 500 separate runs of karma.

I guess I'm what I'm soft-proposing is: what if `nyc` (I'm considering that the coverage engine, I'm not sure if there are even serious competitors for nodejs at the moment...) had built-in support for coverage context.

- Define a new thing, called `context`.  It defaults to `global`.
- Breaking change: the coverage map (i.e. the `__coverage__` or `$$coverage$$` object) has a new top-level map, where the list of files are within a context key:

```
{
    "global": {
        "spec/index-spec.js": {
            "path": "spec/index-spec.js",
            "s": ...,
            "b": ...,
            "f": ...,
        }
    }
}
```

- Export (that is, define on `global` or `window`) a function called `setCoverageContext` that allows any test runner to define the context of whatever coverage comes next.

- When all tests are complete and it's time for `nyc` to report coverage, it now has a broken out map and has a number of options:
  - Merge all contexts together.  This would be identical to today's behavior.  If the test runner doesn't know about `setCoverageContext`, then all coverage will be in one context anyway.
  - File-based: coverage for `x.js` should only be counted by contexts `x-spec.js` or `xSpec.js`.
  - Folder-based: coverage for `/folder/x.js` should only be counted by contexts `/folder/*`.
  - User-defined: allow user to define a strategy function, `covers(context, file): boolean`, that determines whether coverage from that context should count for that file.
 - Whatever strategy is chosen, the merging takes place and reporting happens as normal.

If `nyc` supported this new global function, it'd be up to jasmine, mocha, jest, tap, etc., to support it if they saw fit, and for any alternate coverage engines to mimic it as well.

**Comment by coreyfarrell** [comment]
nyc can't directly support filtered coverage but it does have features to allow the test runner to implement this.  We added an NYC_CONFIG_OVERRIDE environmental variable that can be set by the test runner.  So when the test runner executes `test/x.js` it can include `NYC_CONFIG_OVERRIDE: JSON.stringify({include: ['lib/x.js']})` in the environment.  This would cause the `test/x.js` process to only include coverage for `lib/x.js`.  Important detail for this is that NYC_CONFIG_OVERRIDE must be set by the process spawn, `test/x.js` itself cannot override nyc config because it's too late (nyc is already fully initialized in the subprocess before `test/x.js` is even loaded).  This is how tap implemented it's coverage-map feature (tap uses nyc for coverage).

As far as the browser goes I must point out nyc itself is a node.js tool and has no direct support for the browser (or any other platform that is not node.js).  Any browser coverage is the result of another tool directly using istanbul-lib-instrument or babel-plugin-istanbul in the web server to manipulate the sources, then collecting the __coverage__ variable from the browser and feeding it back to nyc.  So again it would be up to the test runner to restrict coverage per test.  For browser testing this would likely need to be done by filtering the `__coverage__` object after running each test page rather than trying to control which files were instrumented in the first place.

Sorry to disappoint but I think nyc already does everything it can to make this possible, further functionality would have to be implemented by the test framework as tap has done.

**Comment by elliot-nelson** [comment]
Actually, your explanation about how Browser coverage actually gets collected is really helpful - I believe in my case it's a reporter lib I'd want to dig into.

Thanks again for the details above! I'm OK to have this issue closed.
