### ISSUE TITLE
nyc not respecting sourceMappingURL

### ISSUE THREAD

**Issue by basickarl** [istanbuljs/nyc#1128]
https://www.typescriptlang.org/docs/handbook/compiler-options.html under the `mapRoot` option my transpiled .js files looks for source maps in a different directory (this also applies for Webpack).

My transpiled file includes at the bottom: 
`//# sourceMappingURL=http://localhost:9228/application/index.js.map`
However the nyc output is: 
`An error occurred while trying to read the map file at /home/karl/dev/edsc/.build/application/http:/localhost:9228/application/index.js.map`

It just appends it. This is a bug since it clearly states `URL` in `sourceMappingURL`.

I am however suspecting that nyc uses https://github.com/evanw/node-source-map-support so?

**Comment by bcoe** [comment]
@basickarl I don't know that I've ever tried loading source-maps loaded via a URL; perhaps this is better classified as a feature request?

**Comment by basickarl** [comment]
@bcoe It states URL and not Path for example hence it's a bug.

**Comment by coreyfarrell** [comment]
nyc is a node.js tool, there is currently no support for loading from remote URL's.  `sourceMappingURL` is a standard name defined outside nyc (originally by browsers I believe).  The fact that it says URL does not mean that nyc supports URL's.  Again the key point is that nyc is a node.js tool.

I view this as both a bug and an enhancement request.  The bug is that we should not combine absolute URL's with the local path.  Actually supporting load from URL's is an enhancement.
