### ISSUE TITLE
npm advisory #1065 : Prototype Pollution

### ISSUE THREAD

**Issue by TonyJDavies** [istanbuljs/nyc#1151]
Advisory [https://www.npmjs.com/advisories/1065](https://www.npmjs.com/advisories/1065)

The currently published version of `nyc 14.1.1` specifies a devDependency of `lodash ^4.17.11` which has this vulnerability.

**Comment by coreyfarrell** [comment]
As mentioned in the PR the published version of nyc is not vulnerable.  This was an issue for developing/testing nyc itself, not an issue for projects which use nyc.

`npm i nyc` installs lodash via babel, which pulls lodash using a semver range.  If your project is installing a vulnerable version it is due to package-lock.json or yarn.lock preventing an in-range update. `npm audit fix` will resolve this for npm.  For yarn I don't know the equivalent comment but deleting yarn.lock and node_modules then reinstalling should bring in the latest versions of everything.
