### ISSUE TITLE
Arrow function declaration with `async` claimed as uncovered

### ISSUE THREAD

**Issue by Qweritos** [istanbuljs/nyc#1164]
https://github.com/Qweritos/nyc-bug-demo

## Expected Behavior
100% coverage
## Observed Behavior
Line with `async () =>` is claimed as uncovered. 
In same time declarations without `async` or old-style declaration  `async function() {}` are fully covered.
### Troubleshooting steps
- [* ] still occurring when I put `cache: false` in my nyc config

run `npm i && npm test`

## Environment Information
```
 [qweritos@nb2 nyc-bug-demo]$ npx envinfo@latest --preset nyc
 npx: installed 1 in 1.553s

  System:
    OS: Linux 5.2 Arch Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    Memory: 393.55 MB / 15.58 GB
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm

```

**Comment by coreyfarrell** [comment]
Please follow the instructions for [@istanbuljs/nyc-config-babel](https://www.npmjs.com/package/@istanbuljs/nyc-config-babel).  nyc uses babel transformations and things can get a bit complicated when you are using other babel transformations.  The issue is that the other transformations are introducing new code which isn't always reachable, then nyc is reporting coverage against that transformed code.
