### ISSUE TITLE
File changes missing in master branch / 14.1.1

### ISSUE THREAD

**Issue by jChris85** [istanbuljs/nyc#1200]
It seems like that there are some changes missing in the master branch regarding file extentions.

In the `README.md` in the section **Common Configuration Options** it says that the default values for extension are the following file extensions:

```
['.js', '.cjs', '.mjs', '.ts', '.tsx', '.jsx']
```

I also can see in the history that this change was made to a couple of files like `instument.js`, `report.js` and `config-util.js`.

Here is the commit for these changes: https://github.com/istanbuljs/nyc/commit/914b776215ad3ea54f0e46b4ba2904a8a9d4dfdd#diff-04c6e90faac2675aa89e2176d2eec7d8

Seems like something went wrong during merge or the changes where not merged to master at all.

Because of this you have always to add the extension option if you want to support other file extensions then `.js`.

**Comment by coreyfarrell** [comment]
This was merged correctly.  All defaults were recently moved to [@istanbuljs/schema](https://github.com/istanbuljs/schema).  Note this change was not merged to 14.x, it is for 15+ only.  For README.md about 14.1.1 see https://github.com/istanbuljs/nyc/tree/v14.1.1#readme.

**Comment by coreyfarrell** [comment]
Additional note nyc 15.0.0-beta.0 was released yesterday.  For more information see #1104.

**Comment by jChris85** [comment]
Ok I get it. Now I can see that the readme says only js files are the default extensions for version 14.1.1. 

But it is really confusing that the readme for the master branch says something which is not applicable for the lastest stable release, which is 14.1.1

**Comment by coreyfarrell** [comment]
That's how github works, it shows the master branch which is the latest development version of files. :man_shrugging:

Note also https://www.npmjs.com/package/nyc always shows information about the latest stable version.  Github is for development, npmjs.com is for published releases.

**Comment by giovannicanzio** [comment]
That's how github works _by default_, actually.
In repo's settings you can set a base branch where all pull requests refer to.
On my - maybe wrong? - point of view, master branch, especially when it's a base branch, should be in sync with the lastest tag/stable release and, consequently, its readme consequent with what the dev gets while pulling.
I find the project definitely useful and appreciate your job, that's why I share and show confusion with @jChris85 .
Maybe declaring a branching policy could help. In the end best practices apply till you find something more suitable for your specific project.
For the moment, I also find the information provided by the master readme confusing as not complying with what I get in the latest stable version installed by npm.

**Comment by coreyfarrell** [comment]
The base branch setting controls what is shown at https://github.com/istanbuljs/nyc and controls where PR's go, so changing the base branch would create confusion and burden for contributors and maintainers.  One thing I hadn't realized is by default `homepage` of package.json points to the github readme, I thought `npm home nyc` brought people to npmjs.com.  This is something I can address, I'll be pointing it to https://istanbul.js.org/.

**Comment by giovannicanzio** [comment]
That sounds better, thank you.
