### ISSUE TITLE
First line 'Else path not taken'

### ISSUE THREAD

**Issue by mikbry** [istanbuljs/nyc#1225]
The file I used to explain:
https://github.com/Opla/aice.js/blob/master/packages/aice-utils/src/AgentsManager.js
But it occurs on several files here:
https://github.com/Opla/aice.js/tree/master/packages/aice/src

## Expected Behavior
No 'Else path not taken' at the beginning
![Screenshot 2019-11-17 at 19 53 33](https://user-images.githubusercontent.com/395718/69012255-16b46980-0974-11ea-91a5-7f15801dc647.png)
If i add an empty line at the beginning of the file it goes as expected, but my linter doesn't like this ;-).

## Observed Behavior
In my project I got several dummy 'Else path not taken' :
![Screenshot 2019-11-17 at 19 45 54](https://user-images.githubusercontent.com/395718/69012190-65153880-0973-11ea-9b40-5b5d303d5bcb.png)

### Troubleshooting steps
- [ ] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 152.04 MB / 16.00 GB
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm

```

**Comment by coreyfarrell** [comment]
It appears you're using babel 6 and `mocha --require babel-core/register`.  This is not supported, nyc uses babel 7.  I suspect babel 6 is injecting code which is being reported as part of the coverage.  In theory source-map's should cause coverage of generated code to be ignored but that depends on how the source-maps are written (and if babel-core/register is even properly generating source-maps).

In addition you are using `all: true` in your nyc config.  In current versions of nyc this cannot be combined with passing a transformation module to mocha, you would need to pass the transformer to nyc.  This specific issue is fixed in nyc 15 (currently pre-release).

**Comment by mikbry** [comment]
Thanks @coreyfarrell I upgraded to Babel7 and no more ghost reports
