### ISSUE TITLE
No coverage when running with mocha --parallel mode

### ISSUE THREAD

**Issue by curbengh** [istanbuljs/nyc#1328]
## Link to bug demonstration repository
https://github.com/hexojs/hexo/pull/4374

## Expected Behavior
`nyc --reporter=lcovonly mocha --parallel` should produce "./coverage/lcov.info".
`nyc --reporter=text-summary mocha --parallel` should display coverage report.

## Observed Behavior

`nyc --reporter=lcovonly mocha --parallel` generates an **empty** "./coverage/lcov.info".
`nyc --reporter=text-summary mocha --parallel`:

```
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```

### Troubleshooting steps
No issue in mocha's default serial mode.

## Environment Information

```
  System:
    OS: Linux 4.9 Solus 4.1
    CPU: (1) x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
    Memory: 1.53 GB / 2.94 GB
  npmPackages:
    nyc: ^15.0.0 => 15.1.0 

```

".mocharc.yml"
``` yml
color: true
reporter: spec
ui: bdd
full-trace: true
exit: true
require: 
  - "chai/register-should"
parallel: true
```

**Comment by coreyfarrell** [comment]
If things work without using `--parallel` could you cross-post an issue to the mochajs repository so they are aware of this potential issue?  I haven't had a chance to look into the mocha `--parallel` implementation so I'm not sure where the issue comes from.  Please be sure to link that issue to this one.

I'm pretty busy currently so it might be a while before I have a chance to investigate, for now you will probably have to disable parallel for coverage testing.
