### ISSUE TITLE
Coverage is missing when instrumented code loads package.json

### ISSUE THREAD

**Issue by ceberz** [istanbuljs/nyc#1393]
## Expected Behavior

Coverage data for all instrumented files

## Observed Behavior

Coverage data is missing in files that require package.json

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
# paste the output here
npx: installed 1 in 3.81s

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 366.82 MB / 16.00 GB
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  npmPackages:
    nyc: 15.1.0 => 15.1.0 
```
In the project where this problem first happened I tried using fs-lib's readFile() and readFileSync(), thinking maybe the bug had to do with require(), but that didn't help. I'd also see this happen when I loaded other seemingly arbitrary js files, but stuck with loading package.json as the example.

**Comment by coreyfarrell** [comment]
NYC operates in strict mode by default.  The problem is not that you're loading package.json, `package` is a reserved word in strict mode.  The next major version of NYC will produce a parse error in this situation but that is a breaking change.  If you change the variable name it will work.  If you add `'use strict'` to the top of your source it should produce a runtime error.

**Comment by ceberz** [comment]
Thanks!
