### ISSUE TITLE
nyc@7.0.0-alpha3 lcov report broken

### ISSUE THREAD

**Issue by JaKXz** [istanbuljs/nyc#288]
continued from: https://github.com/istanbuljs/nyc/pull/286#issuecomment-228666575

Minimal reproduction: https://gist.github.com/JaKXz/e91baeead7f4ff2df6825abf33327479

Similar [but not necessarily related] error with v6.6.x and the `--all` flag and `__coverage__` plugin: https://github.com/JaKXz/react-redux-starter/tree/d0bc516cdea96e45b75d6ad585bc6c9b6f3fb97c

@bcoe @gotwarlost et al

**Comment by bcoe** [comment]
@JaKXz @gotwarlost interestingly enough, works well with the new `babel-plugin-istanbul`:

```json
{
  "name": "nyc-ava-test",
  "version": "1.0.0",
  "description": "",
  "main": "say.js",
  "scripts": {
    "test": "nyc -r lcov ava"
  },
  "author": "",
  "license": "ISC",
  "babel": {
    "presets": [
      "es2015"
    ],
    "plugins": [
      "istanbul"
    ]
  },
  "nyc": {
    "include": [
      "*.js"
    ],
    "require": [
      "babel-register"
    ],
    "sourceMap": false,
    "instrument": false
  },
  "devDependencies": {
    "ava": "^0.15.1",
    "babel": "^6.5.2",
    "babel-cli": "^6.9.0",
    "babel-plugin-istanbul": "^1.0.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-register": "^6.9.0",
    "nyc": "^7.0.0-alpha.3"
  }
}
```

underlying problem seems to be bad source-map positions, which I know we've bumped into in a few places. Hopefully this will be fixed once the issue @gotwarlost opened on babel itself is addressed, and once we switch source-map functionality over to using Isanbul directly.

If anyone gets bored @novemberborn, @JaKXz, @jamestalmage, would love help wiring up Istanbul's source-maps, such that we can retire nyc's handling of them.

**Comment by JaKXz** [comment]
@kentcdodds this is the same issue you reported :)

**Comment by kentcdodds** [comment]
Ok, I thought it might be :-) Thanks for merging them :-)

**Comment by bcoe** [comment]
@kentcdodds @JaKXz mind giving an update I just published a spin?

`npm cache clear; npm i nyc@next`

We've pulled out source-map support into istanbuljs.

**Comment by JaKXz** [comment]
@bcoe LGTM, not using `babel-plugin-istanbul`.

**Comment by JaKXz** [comment]
I am seeing new issues with `babel-plugin-istanbul`@1.0.1 but it might be because I have an incorrect setup somewhere... let me try to minimally reproduce and I'll make a new issue.
