### ISSUE TITLE
Issue with sourcemap file paths

### ISSUE THREAD

**Issue by KarlPurk** [istanbuljs/nyc#314]
I've noticed that my sourcemap file paths are wrong in the output json file.

After a quick investigation I can see that the paths in the `globals.__coverage__` object are correct, and look like this:

```
/Users/karl.purkhardt/projects/personal/nyc-test/src/calc.ts
```

However, the file paths inside the output json file are missing `nyc-test`:

```
/Users/karl.purkhardt/projects/personal/src/calc.ts
```

In my case, the source files are written in `TypeScript` and I'm using the `ts-node` execution environment as a `mocha` compiler.  

I've created a test project that replicates the issue:
https://github.com/KarlPurk/nyc-test

**Comment by rundef** [comment]
Hey,

I was having the same problem as you. After some investigation, I've located the problem down to this line -> https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L101 - basically ts-node compiles the code into a **temp** directory, so the source maps URLs are relative to that temporary directory - and that's why the sourcemap file paths are wrong when using nyc.

I just sent a pull request to get this fixed : https://github.com/TypeStrong/ts-node/pull/145

**Comment by KarlPurk** [comment]
Nice find @rundef, thanks!

**Comment by bcoe** [comment]
@KarlPurk @rundef this is now fixed for you?

**Comment by rundef** [comment]
Yep, it works fine with the latest version of **ts-node** and **nyc**

**Comment by KarlPurk** [comment]
Yes, it's working for me too. 👍
