### ISSUE TITLE
`nyc report html` should maybe tell users that it’s not what they want?

### ISSUE THREAD

**Issue by addaleax** [istanbuljs/nyc#401]
Okay, probably it’s just me having trained myself to use `istanbul report` over a long time, but I tend to always write `nyc report html` and am confused by the result that there is no actual HTML output.
I’ve begun to catch up always correcting to `-r html`, but maybe other people who transition to `nyc` would find it helpful if `nyc report` outputs a warning when it receives at least one positional argument?

What do you think?

**Comment by coreyfarrell** [comment]
We could add a check to the handler:
```js
  if (argv._.length !== 1) {
    // print `nyc report --help` and exit?
  }
```

@bcoe Adding `.strict()` to the report command builder fails with `Unknown argument: exclude` (I think due to the config in package.json).  I removed `global: false` from the `exclude` option in config-util.js then added `.hide('exclude')` to the report command builder.  This got around the unknown argument error, but then I didn't get any error for `nyc report html`.  Is this a bug in yargs?  The documentation for `.strict()` says `Unrecognized commands will also be reported as errors.`

I think I can make this work but it'll have to wait for some of the work from @AndrewFinlay to be merged.  I'll try to get this into nyc@14 but I can't promise.
