### ISSUE TITLE
nyc does not cover all files

### ISSUE THREAD

**Issue by munkyjunky** [istanbuljs/nyc#434]
When moving from Istanbul + mocha to nyc + mocha my JSX files (plus other JS files) are no longer covered. There are no tests for missing files, however the nyc config should be configured to instrument all files (`--all` flag).

## Expected Behavior
nyc should instrument every file in my `include` stanza, including those without tests

## Observed Behavior
nyc only covers files that have been included in tests

## Forensic Information

**Operating System:** Mac OS, Sierra
**Environment Information:** [output.txt](https://github.com/istanbuljs/nyc/files/566517/output.txt)

```json
"nyc": {
		"require": [
			"babel-register"
		],
		"reporter": [
			"lcov",
			"text-summary"
		],
		"include": [
			"src/**/*.{js|jsx}"
		],
		"exclude": [
			"**/constants/**",
			"**/dispatcher.js",
			"**/_instance.js"
		],
		"sourceMap": false,
		"instrument": false,
		"cache": true,
		"all": true,
		"extension": [
			".jsx",
			".js"
		]
	},
```

**Comment by bcoe** [comment]
Hey @munkyjunky, good timing; I'm just in the process of releasing a fix for this (with the help from @motiz88 who did a lot of the heavy lifting):

`nyc@8.4.0` should do the trick for you.

See this thread: https://github.com/istanbuljs/babel-plugin-istanbul/issues/4

We do however still need to document how `--all` works, which I would love help with:

https://github.com/istanbuljs/babel-plugin-istanbul/issues/67

**Comment by munkyjunky** [comment]
Great news! I've just upgraded to 8.4.0 and everything is now working as expected.

**Comment by bcoe** [comment]
@munkyjunky awesome, glad that the `--all` functionality is doing the trick. If you have any thoughts about what the documentation should look like, would love help with `67` as mentioned.

**Comment by luiso1979** [comment]
This problem came back, there is no way that I can tell nyc to instrument all the files in a certain directory even if not included in any test. 
nyc conf:
    
    "nyc" : {
      "include": [
         "src/**/*.js"
      ],
      "exclude": [
         "**/node_modules/**",
         "**/test/**",
         "**/coverage/**"
      ],
      "all": true
    }

**Comment by dschnare** [comment]
This is happening to me when I have my source directory structured like this:

```
src/
  node_modules/
    a/index.js
    b/
      index.js
      index.test.js
```

I have a `.nycrc` file that looks like this:

```json
{
  "require": [
    "./test/babel-register"
  ],
  "include": [
    "src/**/*.js"
  ],
  "exclude": [
    "!**/node_modules/**",
    "node_modules",
    "**/*.test.js"
  ],
  "reporter": [
    "text",
    "lcov"
  ],
  "sourceMap": false,
  "instrument": false,
  "all": true
}
```
Only module `b` is being covered. 

*NOTE: I wrap the call to `require('babel-register')({ ... opts ...})` because Babel is also heavy handed with regards to ignoring `node_modules` everywhere. My `test/babel-register` looks like the following:*

```js
require('babel-register')({
  babelrc: false,
  ignore: false,
  presets: [
    'es2015'
  ],
  env: {
    test: {
      plugins: [
        require('babel-plugin-istanbul').default
      ]
    }
  }
})
```

Anyway, when I refactor the source code file structure to be like:

```
src/
  a/index.js
  b/
    index.js
    index.test.js
```

And then refactor the `.nycrc` file, everything works as expected (i.e. all files are covered):

```json
{
  "require": [
    "babel-register"
  ],
  "include": [
    "src/**/*.js"
  ],
  "exclude": [
    "**/*.test.js"
  ],
  "reporter": [
    "text",
    "lcov"
  ],
  "sourceMap": false,
  "instrument": false,
  "all": true
}
```

Could you not just ignore the project's `node_modules` folder only (i.e. convention) rather than any path containing `node_modules`? Babel suffers from this heavy handedness as well, but I can circumvent it, albeit with a little elbow grease.

**Comment by dschnare** [comment]
I got around this by creating a `require-all.js` module for now:

```js
const fs = require('fs')
const path = require('path')

const modulesDir = path.resolve(__dirname, '../src/node_modules')
const modules = fs.readdirSync(modulesDir)

modules.forEach(m => require(path.join(modulesDir, m)))
```
Then I use it in the `--require` option for mocha:

`"test": "cross-env NODE_ENV=test nyc mocha --require ./test/require-all src/**/*.test.js"`

*NOTE: I don't add it to the `"require": [ ... ]` array in the `.nycrc` file because it appears to be imported/required more than once.*

**Comment by dschnare** [comment]
Hmm. It appears I spoke a little too soon. It looks like even though there are no tests for module `a` (which I had to require manually), there's a line that is being reported as covered:
![image](https://cloud.githubusercontent.com/assets/893365/26385462/e9ad882c-400d-11e7-93a4-0d2aa289b948.png)

**Comment by bcoe** [comment]
@dschnare regarding the issues with negating the exclusion of `node_modules`; there have recently been changes to this logic here:

https://github.com/istanbuljs/istanbuljs/pull/58

Which I think might give you more flexibility -- If you're continuing to bump into issues please open an issue on [the istanbuljs monorepo](https://github.com/istanbuljs/istanbuljs) so that we can dig into things.

As for the covered line; I believe this is to be expected -- as soon as you required a module, anything in the global scope is evaluated so the `console.log(b)` will have been executed, by virtue of `a` being required.

**Comment by aryzle** [comment]
I am also having an issue with this. In my nycrc I have
```
{
  "include": [
    "src/**/*.js"
  ],
  "all": true,

  "sourceMap": false,
  "instrument": false,

  "lines": 90,
  "branches": 90,
  "check-coverage": true
}
```
but the files in src aren't being checked for coverage unless they partially tested

**Comment by chrisnicola** [comment]
The only way I can currently make this work is to set `"instrument": true` which as I understand things wrong to do when using the babel-istanbul-plugin. But without that it doesn't see any files that have not been required at least somewhere.

**Comment by chrisnicola** [comment]
Ok so with a bit of fiddling around I found that `nyc` must require `babel-register` itself for the `all` function to work regardless of whether the test scripts do this already. This config works:

```
{
  "register": "babel-register",
  "include": [
    "src/**/*.js"
  ],
  "all": true,

  "sourceMap": false,
  "instrument": false,

  "lines": 90,
  "branches": 90,
  "check-coverage": true
}
```

**Comment by bcoe** [comment]
@chrisnicola if you have two secs, would happily accept a patch to the section of the README on  `babel-plugin-istanbul`, highlighting the fact that nyc must perform the instrumentation for `--all` to work.
