### ISSUE TITLE
[8.4.0] failed to instrument

### ISSUE THREAD

**Issue by tleunen** [istanbuljs/nyc#435]
When upgrading from 8.3.1 to 8.4, I'm getting a lot of "failed to instrument" errors.

It starts with files in the dependencies and finish with files in my own project.

Errors like:
```
failed to instrument /Users/xxx/yyy/node_modules/zzzz/node_modules/fbjs/flow/lib/dev.js with error: Unexpected token, expected ; (10:8)
```

**Comment by bcoe** [comment]
@tleunen could you share the project that's having issues? It seems like you're probably using the `--all` flag, and a custom `exclude` rule?

**Comment by tleunen** [comment]
Unfortunately, the project is private so I can't share it.
But I do use the `all` flag and a custom `exclude`. Sorry I should have posted the entire nyc config in the initial message.
```
  "nyc": {
    "sourceMap": false,
    "instrument": false,
    "cache": true,
    "all": true,
    "reporter": [
      "lcov",
      "text",
      "text-summary"
    ],
    "exclude": [
      "test",
      "src/**/__tests__/**"
    ]
  }
```

**Comment by bcoe** [comment]
@tleunen prior to `8.4.0`, `--all` didn't actually do anything when used with `babel-plugin-instrument`. To get things working, I think you'll need to do two things:

1. try upgrading to `nyc@9.x.x` via, `npm cache clear; npm i nyc@next`.
  * this version again excludes `node_modules` by default.
2. if you are using a lazy approach to instrumentation, e.g., `babel-register`., require this in the `nyc` process rather than the test runner process, something like this:

```json
  "nyc": {
    "require": "babel-register",
    "sourceMap": false,
    "instrument": false,
    "cache": true,
    "all": true,
    "reporter": [
      "lcov",
      "text",
      "text-summary"
    ],
    "exclude": [
      "test",
      "src/**/__tests__/**"
    ]
```

☝️ this is required because transpilation must be applie to each file loaded using `--all`.

**Comment by tleunen** [comment]
Thank you @bcoe! :)
