### ISSUE TITLE
Generate coverage for required files passed as args in spawn

### ISSUE THREAD

**Issue by jaridmargolin** [istanbuljs/nyc#463]
Imagine the following code written inside of a testcase.

```
spawn('node', [
   '--require',
   './lib/index.js',
    'test/fixtures/syntax-error.js'
]);
```

I am attempting to generate coverage for `./lib/index.js`.

## Expected Behavior

Coverage is generated for `./lib/index.js`

## Observed Behavior
 
No coverage is generated.

**Comment by jaridmargolin** [comment]
@bcoe do you agree that the expected behavior would be to generate coverage?

I have absolutely no insight into the inner workings of istanbul / nyc, but if you agree with the overall direction, I will take a stab at a PR. Additionally if you had any thoughts / ideas about the implementation, feel free to share :)

Thanks!

**Comment by coreyfarrell** [comment]
This is not directly possible.  I think the problem is that `--require` modules are loaded before nyc can hook the loader system.  To accomplish your goal you will need to pre-instrument your code using:
```
nyc instrument ${PWD}/lib/index.js > lib/index-covered.js
```

Then in your test:
```js
spawn('node', [
   '--require',
   './lib/index-covered.js',
    'test/fixtures/syntax-error.js'
]);
```

FYI the `${PWD}` is needed for now to work around #1014.   Once that is fixed you'll be able to just `nyc instrument lib/index.js > lib/index-covered.js`.
