### ISSUE TITLE
config.include not respected when paths are not in cwd, namely symlinked files

### ISSUE THREAD

**Issue by giannic** [istanbuljs/nyc#472]
## Expected Behavior
`config.include` paths override `test-exclude` lib's explicit ignore of parent paths, `../`

## Observed Behavior
Any file not in `cwd` is ignored.

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/istanbuljs/test-exclude/blob/master/index.js#L60

## Forensic Information

**Operating System:** OSX 10.10.5
**Environment Information:**
The caveat comes in here: I am using [bazel](https://www.bazel.io/) build system to execute nyc. Bazel achieves fast reproducible builds partly by symlinking required files from a `tmp` directly under `/private/tmp`. This means any `relFile` path will start with `../` for any build done in bazel.

At the moment, I forked the repo with a [patch](https://github.com/Medium/nyc/pull/1/files) just to move forward, but I would love suggestion and happy to make acceptable changes upstream if necessary

**node & npm versions:**
v4.6.0
2.15.9

**Comment by bcoe** [comment]
@giannic thanks for reporting this; I'd love to figure a way to better support some common edge-cases like symlinks ... while still preventing weird files from being instrumented, e.g., files outside your project ... seems like there are quite a few edge-cases that would need to be worked through.

**Comment by Wedvich** [comment]
I have a different, though probably still not very common use case, where I use multiple test frameworks for some setup examples. Basically, I have a directory structure like this:
```
tap-nyc
    test
        index.spec.js
    package.json
src
    index.spec.js
```

Using tap-nyc as the working directory, running `nyc tap ./test/**/*.spec.js` passes the test, but no files are discovered by nyc since it's outside the current working directory, even if I've explicitly asked for the source files to be included using `config.include`.

**Comment by JaKXz** [comment]
Looks like this is related to #962
