### ISSUE TITLE
Extend .nycrc configurations

### ISSUE THREAD

**Issue by rcoy-v** [istanbuljs/nyc#503]
Other tools that have similar uses of `.rc` configuration files, like Babel and ESLint, allow you to extend other configuration files. This is a useful option for configuration reuse, when you want to keep mostly the same configuration in multiple projects, and only override a few options.

It doesn't appear that nyc supports this currently. Below is an example of what I would like to do:

node_modules/my-lib/.nycrc
```json
{
    "lines": 95,
    "statements": 95,
    "functions": 95,
    "branches": 95,
    "reporter": [
        "cobertura",
        "lcov"
    ],
    "all": false,
    "check-coverage": true,
    "report-dir": "./coverage",
    "cache": false
}
```

.nycrc
```json
{
  "extends": "./node_modules/my-lib/.nycrc",
  "lines": 80
}
```

**Comment by JaKXz** [comment]
@rcoy-v I'd go one further and say:

```json
{
  "extends": "my-lib",
  "lines": 80
}
```

and you could optionally specify a relative path instead of the module name.

That being said, I think this is a great suggestion! Feel free to take a crack at a PR, but if not hopefully I can take a look later this week.

**Comment by bcoe** [comment]
@JaKXz I like this idea too, but one thing comes to mind @rcoy-v; why don't we add this functionality to [yargs' config handling](https://github.com/yargs/yargs#configobject) and open a feature request on `yargs`, rather than implementing the extend option in `nyc`.

One side-goal I've had with `nyc` is to try to use it to hammer on yargs, and figure out clean abstractions for a complex CLI application.

**Comment by rcoy-v** [comment]
@bcoe To make sure I understand, you are suggesting the syntax for extending configurations is fine. What implements the merging of configuration extensions is yargs, not nyc directly. That is to make extending functionality reusable to any project.

If that is correct, I'm fine either way on where it is implemented.

**Comment by bcoe** [comment]
@rcoy-v yeah; I like the syntax, especially if other projects are converging on it. But it would be nice to implement it in yargs if possible, so that anyone using yargs for loading `rc` files gets the functionality.

**Comment by bcoe** [comment]
@rcoy-v sorry this took so long to build; I really appreciate the work, and I I feel the feature turned out really slick; here's an example:

https://www.npmjs.com/package/@istanbuljs/nyc-config-babel

You can now try things out on the next release candidate of nyc:

`npm cache clear; npm i nyc@next`

👍
