### ISSUE TITLE
Use of --all is broken when instrumentation is disabled

### ISSUE THREAD

**Issue by wbyoung** [istanbuljs/nyc#509]
An attempt was made to fix this in #482 and rolled back in 25aec778cfa6d79fe71077c96b0dde81e6ec3a1f.

See https://github.com/wbyoung/nyc-issue-482-example and discussion on #482 for a full example of the problem.

**Comment by bcoe** [comment]
@wbyoung I think I've got to the bottom of this issue for you:

https://github.com/wbyoung/nyc-issue-482-example

I'm trying to catch up on pull-requests this weekend across a few projects, so haven't had a chance to the exact root cause -- but it seems to ultimately relate to the order of operations that processes are spawned and that babel-register is applied.

Give [this solution a shot](https://github.com/wbyoung/nyc-issue-482-example) and if you confirm that it's working, I'd love help documenting this in the README.

**Comment by wbyoung** [comment]
@bcoe that does work. Thanks so much for the help!

Ideally, I think it'd be nice if it wasn't required. As is, the documentation for getting this set up is pretty clear. I think it'd be better to try to avoid adding a section like:

> If you've got this all set up and working, but you want to use this one flag, make sure you enable this other thing because internally it's being processed in this way.

For the vast majority of users, this will just be noise. If there's an (easy) way to fix it (even if it's months from now), that'd probably be better than complicating the setup docs.

Just my opinion, though.
