### ISSUE TITLE
confused about purpose of NYC vs Istanbul

### ISSUE THREAD

**Issue by ORESoftware** [istanbuljs/nyc#524]
It seems like we can easily get coverage of child processes with something like:

```js
  cp.spawn('istanbul',
  ['cover', execFile, '--dir', coverageDir, '--report', 'lcov', '--'].concat(args));
```

therefore I am confused about what the purpose of NYC is. Also, as an aside, did Istanbul swallow/adopt the NYC project? I thought that NYC was independent, but now it's part of the IstanbulJS org.

**Comment by bcoe** [comment]
@ORESoftware the original purpose of nyc was to allow a user to capture test coverage, regardless of how programs are spawning subprocesses, without requiring any changes in the instrumented code. This is useful for:

* tests that spawn sub-processes, e.g., in the [yargs codebase](https://github.com/yargs/yargs/blob/master/test/integration.js) we have a set of tests that spawn the CLI.
* some test frameworks, e.g., ava, tap., run their tests within subprocesses -- nyc provides a simple mechanism for adding coverage to these technologies.

As for the relationship between istanbul and nyc; nyc did start separately, but we decided to merge the two projects together as Istanbul moved towards a 2.0 API ... the idea being that nyc would provide the command line interface to this new API.

Things are still a little bit confusing, since we haven't finished the complete migration, but currently the idea is essentially that nyc would be the all-in-one, simple-to-use, command line interface for the Istanbul 2.0 API.

**Comment by the1mills** [comment]
Thanks a ton for the info, and yeah this is pretty confusing. I am writing a test lib similar to TapJS and would like to have "batteries included" support for Istanbul/nyc.

I actually would have thought that nyc would somehow monkey patch child_process, which is why you'd require 'nyc' instead of requiring 'istanbul' but I guess that's not the case?

Is there anything that describes the difference between the nyc command line and the Istanbul command line?

Sounds like what youre saying is that

A. The distinction between the two is mostly the difference between command line behavior.

B. nyc will be the command line interface to istanbul?

If B is true, will the Istanbul command line be maintained?

Thx!

**Comment by bcoe** [comment]
_I actually would have thought that nyc would somehow monkey patch child_process, which is why you'd require 'nyc' instead of requiring 'istanbul' but I guess that's not the case?_

`nyc` does monkey-patch `child_process.spawn` and `child_process.exec`, as well as monkey-patching the require statement:

_spawn hook:_

https://www.npmjs.com/package/spawn-wrap

_require hook:_

https://www.npmjs.com/package/istanbul-lib-hook

_Is there anything that describes the difference between the nyc command line and the Istanbul command line?_

https://github.com/istanbuljs/nyc/issues/309 this was the original document written to help along the migration process.

_nyc will be the command line interface to istanbul?_

Currently nyc is the most actively maintained command line client that interacts with the Istanbul 2.0 API.

_I am writing a test lib similar to TapJS and would like to have "batteries included" support for Istanbul/nyc._

node-tap's coverage support is [facilitated by nyc](http://www.node-tap.org/coverage/); I originally worked fairly closely with the tap project, part of our goal being to make a coverage tool that worked well with coverage.

As for other prior art:

[facebook's jest](https://github.com/facebook/jest) uses `babel-plugin-istanbul`, and the Istanbul 2.0 APIs directly to facilitate test coverage -- and is probably worth looking at.

Also, to cut down on confusion, we're looking at combining most of the core istanbul libraries into a [mono-repo](https://github.com/istanbuljs/istanbuljs) so that there are less individual projects to keep track of.

**Comment by ORESoftware** [comment]
thanks, will digest and let me know if I have any further inquiries! really appreciate the info

**Comment by seanpoulter** [comment]
As one of the confused parties, would you make a note in the repo description about the relationship with nyc @gotwarlost? I'm happy to submit a PR if you'd like something in the README.

**Comment by marcusjwhelan** [comment]
Does anyone have an example of using jest to create a repo badge for coverage? It seems with coveralls you can use it but there is no example of how [node-coveralls issue 126](https://github.com/nickmerwin/node-coveralls/issues/126)

**Comment by bcoe** [comment]
@marcusjwhelan you should be able to pass an `lcov-text` reporter to jest, and then pipe this to coveralls (mind opening an issue on Jest, this would be great to document; please feel free to flag me).

@seanpoulter @ORESoftware we now have a deprecation notice on gotwarlust/istanbul which I think is a good start.

**Comment by torarebel** [comment]
What's in a name?  (This is tangential - don't read if you are not interested)
I find it interesting that the usage of Istanbul says to use nyc to get Istanbul installed and use nyc as the way to get Istanbul coverage on your mocha testing.
What is the connection between Istanbul and nyc?  I don't know except for this:
The They Might Be Giants song "Istanbul (Not Constantinople)" contains a line that says "even old New York was once New Amsterdam, why they changed it, I can't say, people just liked it better that way" - so maybe, in some strange universe, TMBG was predicting the (sometimes arbitrary) way we name things and then change them!  Sorry for letting my geek show there!
Just a reminder to give things a cool, catchy name like Istanbul rather than something boring like JavaScript Coverage Utility, because people will like it better that way - and in the end it doesn't really matter.  (nothing really matters ... to me  - don't get me started!)

**Comment by ShadSterling** [comment]
I'm trying to apply the usage of istanbul in an oldish project to a new project and getting errors, so I was looking for documentation of how to migrate.  Searching for "moving from istanbul to nyc" was about as helpful as you'd expect. 

Is there any documentation about migrating?

**Comment by jwk15** [comment]
I'm with @ShadSterling. I'm trying to migrate a codebase I inherited from `instanbul-combine` to `nyc`. I can't find any relevant documentation. And the only way to ask questions (other than tacking them onto an old issue like this) is to open a whole new issue, for which a `nyc-bug-demo` repository is "mandatory." And it seems that no one answers questions on StackOverflow regarding istanbul/nyc.

Btw the link in the nyc documentation to the "community slack" is broken: "No such app".

I guess it's no surprise that the documentation so deficient when you erect so many barriers to making suggestions and asking questions.

**Comment by ShadSterling** [comment]
I did eventually figure out how to use `nyc` for at least one project, and once I got the scripts right it worked well.  I think these are the relevant bits:

- run tests (mocha): `nyc --reporter html --reporter json mocha --mocha-options ...`
- generate coverage reports: `nyc report --reporter html --reporter json`
- check coverage levels: `nyc check-coverage --branches 100 --functions 100 --lines 100 --statements 100`
- clear everything to start fresh: `rm -rf reports .nyc_output coverage ...`

Also, there's no `remap` fiddling anymore with `nyc`, which I think is because `source-map-support` took care of that.

I haven't been actively working on these things for a while now, so what I set up then might not work now.  I'm mostly going by https://github.com/ShadSterling/Awaitable/blob/master/package.json
