### ISSUE TITLE
Question/feature - Interpret hashbang

### ISSUE THREAD

**Issue by ORESoftware** [istanbuljs/nyc#540]
This is a feature request - I opened the issue with gotwarlost/istanbul, but I think maybe I should be opening it here instead

https://github.com/gotwarlost/istanbul/issues/788

First and foremost this is a question...I am wondering if Istanbul will currently interpret the hashbang in a file, for example if we have this:

`#!/usr/bin/env mocha`

instead of

`#!/usr/bin/env node`

such that when we run:

`istanbul cover <file>`

istanbul can execute the file with mocha instead of node (or whatever the executable might be besides node).

this would be very nice and is something I am obviously looking for.
Perhaps Istanbul already does this, I tested it though, and it doesn't seem to work.

**Comment by bcoe** [comment]
@isaacs and @addaleax have done a lot of the work around this specific `nyc` functionality -- I definitely think it would be cool.

We're actually a few versions behind `spawn-wrap`, which is the library that facilitates `#!/usr/bin/env node`.

**Comment by ORESoftware** [comment]
Yeah, I see, I guess supporting windows will make it a bit harder

**Comment by addaleax** [comment]
So… I’m a bit torn on whether nyc should do this; on the one hand, it’s clear why this feature would make sense. On the other hand, what `nyc` supports right now is that it either lets you replace `node` with `nyc` in a command line and everything just works, or you prepend `nyc` to the command line. Implementing this feature would add a third such mode, and I’m a bit weary of the inconsistency/added complexity…

(A little aside: There’s some movement on adding support for pre-loading modules via environment variables on the Node core side, so `spawn-wrap` might not be necessary anymore at some point ^_^)

**Comment by isaacs** [comment]
@addaleax 

> (A little aside: There’s some movement on adding support for pre-loading modules via environment variables on the Node core side, so spawn-wrap might not be necessary anymore at some point ^_^)

It'll still be required if you do `spawn(node, [jsfile], { env: { foo: 'bar' } })` because it won't get passed in.  But, the spawn-wrap usage can potentially be simpler, because all it has to do is enforce an environment var rather than inject argv.

Currently, spawn-wrap will _not_ detect a shebang line that is itself a shebang script invoking node.  That could be added pretty easily, care to open an issue over at https://github.com/tapjs/spawn-wrap/issues?  Thanks!

**Comment by coreyfarrell** [comment]
I just did some experimentation with the following `shebang.js` file:
```js
#!/usr/bin/env mocha
console.log(it);
```
Then I added scripts to a package.json where mocha and nyc were already installed:
```json
{
  "scripts": {
    "shebang": "./shebang.js",
    "shebang-nyc": "nyc --cache=false --all=false ./shebang.js"
  }
}
```

For both `npm run shebang` and `npm run shebang-nyc` I could see the following output:
```
{ [Function] only: [Function], skip: [Function], retries: [Function] }


  0 passing (1ms)
```

This output proves that `shebang.js` was being run by mocha, without mocha the `it` function would be undefined. In the case of `shebang-nyc` it also displayed 100% coverage.  So I'm unsure how/when but it seems like this issue is fixed.  @ORESoftware if you can still reproduce the issue with latest nyc please open a new ticket including a minimal reproduction repository.
