### ISSUE TITLE
No coverage is reported

### ISSUE THREAD

**Issue by equinoxel** [istanbuljs/nyc#568]
I've got a sample project using TypeScript, mocha and nyc. Tests execute successfully, but can't get coverage to report properly.

Is it something I'm missing?

## Expected Behavior
When running `npm test`, a report should be created with coverage for all called methods

## Observed Behavior
The report is created but it states none of the code is covered

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/equinoxel/mocha-nyc-ts

The result with `all=true` is:

File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
All files   |        0 |        0 |        0 |        0 |                |
 src        |        0 |      100 |      100 |        0 |                |
  main.ts   |        0 |      100 |      100 |        0 |            1,3 |
 src/common |        0 |        0 |        0 |        0 |                |
  logger.ts |        0 |        0 |        0 |        0 |... 27,29,31,34 |

The result with `all=false` is:

File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |

## Forensic Information

**Operating System:** Windows 7.
**Environment Information:** https://gist.github.com/equinoxel/8f06611baebe6fcd7c2c9a7596fe9b01

**Comment by lukasoppermann** [comment]
I got the same issue, on mac. Is there any solution for this yet?

**Comment by bcoe** [comment]
@equinoxel the underlying problem is that `mocha-electron` is opening and executing tests in a Chromium context, outside of nyc's ability to instrument the source, see:

https://github.com/jprichardson/electron-mocha/issues/19

For the time being, you would need to pre-build all the files, and use  `nyc instrument` to instrument them for test coverage -- at which point you can run the test suite against the built files rather than using `ts-register`.

It might also be worth adding your two cents to the `electron-mocha` issue linked above -- perhaps `electron-mocha` could apply require hooks as it pulls in code?

@lukasoppermann mind opening a separate issue, with reference to your test config? it's likely a different issue unless you're using `electron-mocha`.
