### ISSUE TITLE
`--all` does not work for pre-instrumented files

### ISSUE THREAD

**Issue by ljharb** [istanbuljs/nyc#594]
I've read through #333 and https://github.com/istanbuljs/babel-plugin-istanbul/issues/4.

I've not been using "include" at all in my `.nycrc`, only "exclude". So far, everything's worked fine.

I just refactored so that a file in `src` is no longer imported anywhere, but is left behind intentionally to avoid a breaking change. This file now does not appear in my coverage reports.

Adding `--all`, or `"all": true` to `.nycrc`, or adding `"include": ["src"]` - none of these seem to make the never-imported file show up at all (which would hopefully correctly indicate it has zero coverage).

(I'm using `babel-plugin-istanbul` as well to instrument my code during tests, if that matters)

**Comment by bcoe** [comment]
@ljharb I can confirm that `--all` is working as expected with the latest version of nyc and babel-plugin-istanbul:

contents of `.nycrc`:

```json
{
  "sourceMap": false,
  "instrument": false,
  "require": [
    "babel-register"
  ]
}
```

contents of `.babelrc`:

```json
{
  "presets": ["es2015"],
  "plugins": ["babel-plugin-istanbul"]
}
```

If I had to venture a guess, perhaps it's an order of operations issue; make sure `babel-register` is loaded by `nyc` so that it can instrument files during the `--all` walk.

If this isn't the issue, could you share the specific repo having trouble?

**Comment by ljharb** [comment]
I think perhaps the difference is that I'm running tests on the build output explicitly - not directly on the source files - so I'm not using babel-register at all; I'm instead letting nyc use the companion source maps on the babel output to generate the coverage report.

The branch in question is [here](https://github.com/airbnb/prop-types/tree/prop-types-exact); I'm looking for `src/forbidExtraProps.js` to show up as uncovered in `coverage/index.html` after `npm run coverage`.

**Comment by novemberborn** [comment]
@ljharb I'm just running into the same issue. I don't know how `nyc` would deal with this, so instead I'm working around it.

Here's my `nyc` config:

```json
  "nyc": {
    "cache": true,
    "exclude": [
      "packages/*/test.js",
      "packages/app/server.js",
      "webpack.config.js"
    ],
    "include": [
      "packages/*/src/**/*.js",
      "packages/*/*.js"
    ],
    "instrument": false,
    "reporter": [
      "html",
      "lcov",
      "text"
    ],
    "sourceMap": false
  },
```

Note how instrumentation is disabled. I have a monorepo setup: some packages are compiled using Babel, others contain a webpack config, and others are plain JavaScript. Building is done in a `build.sh` helper script. Istanbul instrumentation is added based on the `BABEL_ENV`.

I have a `test.sh` helper script which runs the tests in the various packages.

Then there's the `coverage.sh` helper script:

```bash
BABEL_ENV=coverage scripts/build.sh
nyc --silent scripts/test.sh "$@"
nyc --silent --no-clean scripts/require-all.js
for entry in packages/*; do
  if [ ! -d "${entry}/src" ]; then
    nyc --silent --no-clean --include="${entry}/**/*.js" --instrument -- node -e ''
  fi
done
nyc report
```

`nyc --silent scripts/test.sh "$@"` is pretty straight-forward, but like you found it does not create reports for *all* files. Hence `scripts/require-all.js`:

```js
#!/usr/bin/env node

const path = require('path')
const globby = require('globby')

const {nyc: {include, exclude}} = require(path.resolve(__dirname, '../package.json')) // eslint-disable-line import/no-dynamic-require

const patterns = [...include, ...exclude.map(p => `!${p}`)]
for (const dep of globby.sync(patterns)) {
  try {
    require(path.resolve(__dirname, '..', dep.replace(/\/src\//, '/build/'))) // eslint-disable-line import/no-dynamic-require
  } catch (err) {}
}
```

This attempts to require all included (and non-excluded) files, based on the `nyc` config in the `package.json` file. It loads the built files, which `nyc` knows how to map to the original sources.

Finally `nyc --silent --no-clean --include="${entry}/**/*.js" --instrument -- node -e ''` runs `nyc` on the packages that do not have a `src` directory. `--all` and `--instrument` are explicitly enabled. `-- node - e ''` is there because `nyc` wants to run something.

The final `nyc report` creates a combined report.

**Comment by mrchief** [comment]
I do something similar to workaround this :unicorn: option:

```
require('require-directory')(module, '../../app', {
  extensions: ['js', 'jsx']
})
```

This requires all source files and then nyc reports missing correctly. Note that with this, you do not need to specify `--all` or require babel-register again by nyc (so it speeds up things bit).

**Comment by bcoe** [comment]
@mrchief @novemberborn @ljharb would definitely love to support this use-case better -- maybe we can brainstorm something in this thread ... nyc is supposed to work like magic for _everything_.

**Comment by mrchief** [comment]
@bcoe I'll try to setup a dummy repo tonite. I've battled this issue for many months now and I'd love to see a solution that works with the `require-directory` workaround.

**Comment by ljharb** [comment]
I would assume `--all` first grabs up every filename in `include` (lacking that, every filename), and removes the `exclude` ones, adds them as having zero coverage, and then runs the coverage as normal.

@bcoe what am I missing with this approach?

**Comment by mrchief** [comment]
Made this very simple repo to reproduce this problem: https://github.com/mrchief/nyc-all-demo

However, in the above repo, adding 

```
"require": [
      "babel-register"
    ]
```

to nyc makes it work (just like the documentation says). So I think there is something else that's messing up things (besides the fact that babel-register may have to be loaded twice). 

I'm going to see if I can make things break (where requiring babel-register won't help either).

**Comment by novemberborn** [comment]
With `instrument: true`, does `nyc` obtain coverage just by doing the instrumentation, without loading the file?

My issue is that `instrument` is `false`, and the files are written to a different directory. They need to be loaded for `nyc` to pick up the empty coverage report.

**Comment by mrchief** [comment]
Got it:  run ` npm run test:cov` in this https://github.com/mrchief/nyc-all-demo/commit/b393d3306052a16a117421cd6b30ebfd906afc34 and it stops reporting all files.

Maybe this isn't correct usage?

**Comment by bcoe** [comment]
@mrchief @novemberborn @ljharb `--all` will only work if nyc is performing the instrumentation itself; this is because as indicated in this thread, nyc loads the files and pulls out the populated empty instrumentation object.

@mrchief in your specific case, the problem is that the top level nyc process needs to perform the instrumentation, so this would fix things:

```json
{
  "name": "nyc-all-demo",
  "version": "0.0.1",
  "description": "Demo repo to brainstorm nyc --all issue",
  "main": "index.js",
  "repository": "https://github.com/mrchief/nyc-all-demo.git",
  "author": "mrchief <mrchief_2000@yahoo.com>",
  "license": "MIT",
  "scripts": {
    "test": "cross-env NODE_ENV=test nyc ava"
  },
  "dependencies": {},
  "devDependencies": {
    "ava": "^0.19.1",
    "babel-core": "^6.24.1",
    "babel-plugin-istanbul": "^4.1.4",
    "babel-plugin-lodash": "^3.2.11",
    "babel-preset-env": "^1.4.0",
    "babel-register": "^6.24.1",
    "cross-env": "^4.0.0",
    "nyc": "^11.1.0",
    "rimraf": "^2.6.1"
  },
  "ava": {
    "files": [
      "src/**/*.test.js"
    ],
    "babel": "inherit"
  },
  "nyc": {
    "sourceMap": false,
    "instrument": false,
    "cache": true,
    "check-coverage": true,
    "reporter": [
      "html",
      "text"
    ],
    "require": [
      "babel-register"
    ],
    "all": true,
    "exclude": [
      "**/*.test.js",
      "**/node_modules/**"
    ]
  }
}
```

I'm not sure what the best solution would be if someone is precompiling the source-files, which circumvents the step that pre-loads files into memory so that we can pull out their __coverage__ header.

Any thoughts @jamestalmage feels like we might need an additional flag for this edge-case.

**Comment by bcoe** [comment]
whoops, flagged @jamestalmage instead of @novemberborn on this issue (sorry James 👋) getting my AVA contributors mixed up.

**Comment by ljharb** [comment]
@bcoe ok, then that means `--all` won't work for my use case, as I intentionally prebuild and preinstrument the code myself. Is there any possibility of an option that allows nyc to locate *every file on disk* in an included dir, since that's what "all" means to me intuitively?

**Comment by novemberborn** [comment]
> Is there any possibility of an option that allows nyc to locate every file on disk in an included dir, since that's what "all" means to me intuitively?

We'd have to parse the file to extract the coverage header. Loading the file may lead to unexpected code execution.

**Comment by ljharb** [comment]
I'm confused; I'm merely suggesting taking every filename (no parsing) and adding it as having zero coverage, and then overlaying the normal coverage on top of that.

**Comment by bcoe** [comment]
> We'd have to parse the file to extract the coverage header. Loading the file may lead to unexpected code execution.

We're actually already doing this with the `--all` functionality, it does a `noop` require and extracts and stores the coverage header from the file, if I'm recalling correctly. I'm not 100% sure why @ljharb's approach would not be working; Perhaps the issue is that the transpiled code is in an excluded folder, e.g,. `/dist`?

It's probably not a huge amount of work to better support @ljharb's use-case, but it might take some fiddling to get source-maps, etc,. working as expected. Here's the logic that handles `--all`:

https://github.com/istanbuljs/nyc/blob/master/index.js#L173

Note how it swaps out the require statement for an empty function, so that code doesn't execute; any ways, would love supporting @ljharb's use-case if anyone feels like digging in ... there's even a new [slack I've launched for coordinating work](http://devtoolscommunity.herokuapp.com/).

**Comment by novemberborn** [comment]
> We're actually already doing this with the --all functionality, it does a noop require and extracts and stores the coverage header from the file, if I'm recalling correctly.

Best I can tell, [`istanbul-lib-instrument`](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-lib-instrument) stores the coverage header for the last file it covered. That's then accessed as part of `NYC#addAllFiles()`.

> Note how it swaps out the require statement for an empty function, so that code doesn't execute;

I'm not sure why the `fakeRequire` logic is there, perhaps so that `addFile()` can be used for both `--all` and normal scenarios. It seems unnecessary and a bit messy though. I doubt it's even necessary since `addAllFiles()` doesn't seem to execute code anyway.

---

> I'm not 100% sure why @ljharb's approach would not be working; Perhaps the issue is that the transpiled code is in an excluded folder, e.g,. /dist?

Logging `console.error(filename, !!lastCoverage)
` at https://github.com/istanbuljs/nyc/blob/v10.3.2/index.js#L179 shows that nyc fails to instrument a number of source files:

```
~/prop-types/src/and.js false
~/prop-types/src/between.js false
~/prop-types/src/childrenHavePropXorChildren.js false
~/prop-types/src/childrenOf.js false
~/prop-types/src/childrenOfType.js false
~/prop-types/src/childrenSequenceOf.js false
~/prop-types/src/componentWithName.js false
~/prop-types/src/elementType.js false
~/prop-types/src/explicitNull.js false
~/prop-types/src/forbidExtraProps.js false
~/prop-types/src/helpers/getComponentName.js false
~/prop-types/src/helpers/isInteger.js false
~/prop-types/src/helpers/isPlainObject.js false
~/prop-types/src/helpers/isPrimitive.js false
~/prop-types/src/helpers/renderableChildren.js false
~/prop-types/src/helpers/typeOf.js false
~/prop-types/src/helpers/wrapValidator.js false
~/prop-types/src/index.js false
~/prop-types/src/integer.js false
~/prop-types/src/keysOf.js false
~/prop-types/src/mocks/index.js true
~/prop-types/src/mutuallyExclusiveProps.js true
~/prop-types/src/mutuallyExclusiveTrueProps.js true
~/prop-types/src/nChildren.js true
~/prop-types/src/nonNegativeInteger.js true
~/prop-types/src/nonNegativeNumber.js true
~/prop-types/src/numericString.js true
~/prop-types/src/object.js true
~/prop-types/src/or.js true
~/prop-types/src/range.js true
~/prop-types/src/restrictedProp.js true
~/prop-types/src/sequenceOf.js true
~/prop-types/src/shape.js true
~/prop-types/src/uniqueArray.js true
~/prop-types/src/uniqueArrayOf.js true
~/prop-types/src/valuesOf.js true
~/prop-types/src/withShape.js true
```

I haven't dug further to see why those files are not being instrumented, but say `~/prop-types/src/and.js` does end up being covered after `npm run coverage` completes. Presumably nyc receives the instrumentation when the build files are required during the tests.

Note that nyc's instrumentation isn't disabled in @ljharb's branch.

---

The problem I'm describing is where I'm applying `babel-plugin-istanbul` in a precompile step and I've actually disabled nyc's instrumentation. A solution for my use case would be if nyc could detect, through AST parsing, that files already contain coverage headers, and use those in its results. This does seem to be different from @ljharb's problem though.

**Comment by bcoe** [comment]
@novemberborn @ljharb aha, yes; instrumentation should definitely be disabled for `nyc` (using `instrument: false`) if you're using the `istanbul` plugin.

**Comment by ljharb** [comment]
Disabling instrumentation (and source maps, it seems) doesn't seem to change anything - `src/forbidExtraProp.js` still isn't showing up as uncovered.

**Comment by cgalvarez** [comment]
Hi everyone. l've just landed here with this exact problem.

As a quick dirty hack, I've created a fake spec which requires **all** my (instrumented) source files that should be covered, as follows:

```javascript
require('../.instrumented/file1');
require('../.instrumented/file2');
```

It works as a temporary fix, because all `istanbul/nyc` needs is your manually pre-instrumented files to be required in order to be included in the coverage report. That spec file doesn't need any more than the `require()`s.

Hope it can help anybody in the meanwhile of developing a more elegant way to address this issue.

If you think this is a proper solution, I may make a PR to document it in the `README.md`.

**Comment by mukulkhanna** [comment]
I dont know if this is the right place to ask or not, but can anyone please explain what the `sourceMap` property is for? Why is it set to `false` ? and what it does ? Thanks :)

**Comment by DanTup** [comment]
Did anyone get a solution to this? I'm facing the same issue. My project is a VS Code extension written in TypeScript. Because of how VS Code loads the tests, nyc can't instrument them on the fly so I'm doing this:

1. Compile the TS to JS
2. Pre-instrument the JS with `nyc instrument`
3. In my test teardown, write `__COVERAGE__` to disk
4. Use `istandbul-remapper` to fix up source mapping back to ts
4. Run `nyc report` to generate `lcov`

The issue is that any file that wasn't loaded in the test run doesn't get included when I write `__COVERAGE__` to disk and therefore doesn't show in the report. The missing files *are* instrumented.

I've got CodeClimate set up and as things are, if someone sends a PR that loads a file that wasn't loaded before, it blames them for adding a ton of uncovered code (when in reality it was already uncovered, just missing from the report).

Any suggestions welcome!

**Comment by DanTup** [comment]
PS. If there's a way I can just pull nyc into my tests (by editing the my test setup file) to avoid manually instrumenting and/or writing `__COVERAGE__` etc., please let me know, as I'd rather not be maintaining this additional code myself! (I'm not sure it'd solve this problem though?)

**Comment by DanTup** [comment]
I just had the idea that maybe I can ask nyc to write coverage using `--all` for a dummy run (eg. just run `npm --version`), so I tried this:

```
./node_modules/.bin/nyc npm --version --all -e .ts --include **.*
```

However, it results in a completely empty json file. If someone can explain why that doesn't work (I would expect, based on comments above, for it to write empty coverage for every file since I pass `--all`). If I could make that work, I could run it before my tests, and then my `.nyc_output` folder will end up with an empty coverage file along with the real ones, which will give the correct results when they all merge together running the report.

**Comment by DanTup** [comment]
Ok, got further.. I put the args in the wrong place. So now if I run:

```
./node_modules/.bin/nyc --all --include out/src npm --version
```

I get a full list of files in my coverage (obviously this all returns zeros, but that's expected). However, it also outputs a report that I don't want at this point, and sending `--silent` seems to stop it writing the coverage into `.nyc_output`. If I can fix that, I think I'm sorted.

**Comment by DanTup** [comment]
Ok, I did it! The whole thing is a mess, but that's been the whole nvy/istanbul/remap story so far anyway :(

Here's the changes I had to make if they're useful to anyone:

https://github.com/Dart-Code/Dart-Code/commit/3ec4973dde00335033aad2820d29a4c2b7b7a518
https://github.com/Dart-Code/Dart-Code/commit/c9ee2a56e6041ebfb11a8ccffd44aed010b746ff

**Comment by LeonDWong** [comment]
Similar problem here, nyc will output zero percent coverage result when test files importing source file (test result is fine) but perform normally once importing builded files instead of source files, no clue.....

**Comment by the-t-in-rtf** [comment]
There will always be edge cases where nyc can't handle everything seamlessly.  Just to give people another option, it's also possible to:

1. Add a wrapper or rollup test script that hooks into your test stack's lifecycle and looks for global.__coverage__ when all tests finish.  Configure that to save the coverage data somewhere.
2. Instrument everything to a separate directory using `nyc instrument`.
3. Copy the config files and other non-instrumented content to that directory.
4. Run the wrapper script created above to run your tests and collect coverage data.
5. Run `nyc report`, `nyc check-coverage`, et cetera against the coverage data.

At least for QUnit and electron, this worked well for us.

**Comment by ljharb** [comment]
bump.

**Comment by coreyfarrell** [comment]
@ljharb I took a quick peek at https://github.com/airbnb/prop-types, could you see if this is still an issue with latest istanbul/nyc?  Specifically nyc@10 is very old (sorry this issue has fallen through the cracks).  I see the greenkeeper note saying you've blocked nyc/mocha updates due to not supporting node 4, but you're using babel 7 and babel-plugin-istanbul@5 which also do not support node 4.

**Comment by ljharb** [comment]
@coreyfarrell that's a fair point; that particular repo can update nyc to the latest node-4-supporting one (altho i have plenty of other repos for which that's not an option).

**Comment by ljharb** [comment]
Nothing is ever stale, thanks.

**Comment by coreyfarrell** [comment]
not true that nothing ever becomes stale, but this ticket won't get flagged stale again.
