### ISSUE TITLE
Best way to manually write coverage file when nyc's hooks don't work?

### ISSUE THREAD

**Issue by jedwards1211** [istanbuljs/nyc#607]
For one reason or another, my integration tests for [crater](https://github.com/jcoreio/crater) have been failing to report coverage on some files.  I added some debug print statements to `writeCoverageFile` in `nyc/index.js`, and I discovered that sometimes the coverage it finds is empty (`{}`).  But if I print `global.__coverage__` elsewhere, before nyc's exit hook, it's not empty...

So I created and required this module in each of my subprocesses and I got all the coverage again:
```js
function shutdown() {
  if (process.env.BABEL_ENV === 'coverage') {
    try {
      const NYC = require('nyc')
      new NYC().writeCoverageFile()
      console.log('wrote coverage file')
    } catch (error) {
      console.error(error.stack) // eslint-disable-line no-console
    }
  }
  process.exit(0)
}

process.on('SIGINT', shutdown)
process.on('SIGTERM', shutdown)
```
But creating a new instance of `NYC` doesn't seem ideal -- should there a way to get access to the instance of `NYC` created by `nyc/bin/wrap`?  `global.__nyc__`?

Somehow, mysteriously, `global.__coverage__` seems to be getting overwritten between the time these hooks run and `nyc/bin/wrap`'s `onExit` hook runs.  I assume there's a bug in nyc, but I also assume it's going to be difficult to create a minimal repro for it, and I assume doing something when a process gets signaled or right before it exits will always be fraught with difficulties, so I'm planning to rely on manually reporting my coverage now.

**Comment by bcoe** [comment]
@jedwards1211 that pseudo code you've written for outputting coverage reports is almost identical to what's already happening inside nyc to facilitate writing reports via the module [signal-exit](https://www.npmjs.com/package/signal-exit).

I think the code you shared in this issue will cause more issues, because you're now creating a race condition between `nyc`, your actual program, and your own logic to output `__coverage__`.

I would definitely instead try to see if you can hunt down exactly where the `__coverage__` is being reset on you -- there's no logic in nyc that ever resets this object, so its my hunch that there's an odd interaction happening between crater, and nyc's signal-handling.

**Comment by bcoe** [comment]
@jedwards1211 a few things I might check:

* what globals are set at the time when the coverageFinder method is called: https://github.com/istanbuljs/nyc/blob/bbadc1f198bfc060940a040bb604ad2474109ed8/index.js#L402
* what happens if you configure an alternative coverage variable, just out of curiosity: `https://github.com/istanbuljs/nyc/blob/bbadc1f198bfc060940a040bb604ad2474109ed8/lib/instrumenters/istanbul.js#L10`.

**Comment by bcoe** [comment]
@jedwards1211 I would love to get to the bottom of this, and will happily help land any patches that it takes.

**Comment by jedwards1211** [comment]
@bcoe I'm confused what you mean by an odd interaction between crater and nyc's signal handling.  My code never resets `__coverage__` either, so what would?  Or might the signal handler be getting called in a weird context?

**Comment by coreyfarrell** [comment]
Sorry for the lack of responses, it's very difficult to troubleshoot such a large/complex project.  It would be very helpful if we could find a smaller test-case to demonstrate the issue.  That said nyc has seen a great number of updates since this ticket was open, including replacement of babel 6 with babel 7.

One thing I'm noticing is that you were using `babel-node` and having mocha perform the require of babel-register.  I suspect that to get NYC working properly you may need to have NYC perform the include of `@babel/register` and use `node` directly.

If you wish to pursue this further we will need to see an updated repository based on the current versions of nyc and babel.  In addition it would be extremely helpful to see a reproduction in something much less than `crater` itself.  nyc maintainers are volunteers and we have very limited time to learn the inner workings of other projects.
