### ISSUE TITLE
Config path is an array

### ISSUE THREAD

**Issue by suculent** [istanbuljs/nyc#631]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior

Run normally.

## Observed Behavior

Fails on starting nyc from any path.

```
$ nyc
path.js:28
throw new TypeError('Path must be a string. Received ' + inspect(path));
^

TypeError: Path must be a string. Received [ '.nycrc', '.nycrc.json' ]
at assertPath (path.js:28:11)
at Object.resolve (path.js:1167:7)
at join (/usr/local/lib/node_modules/nyc/node_modules/find-up/index.js:11:14)
at Function.module.exports.sync (/usr/local/lib/node_modules/nyc/node_modules/find-up/index.js:43:12)
at Object.Config.loadConfig (/usr/local/lib/node_modules/nyc/lib/config-util.js:17:23)
at Object. (/usr/local/lib/node_modules/nyc/bin/nyc.js:23:25)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)

10:46:09 {master} $ node -v
v8.1.4
```

## Bonus Points! Code (or Repository) that Reproduces Issue

http://github.com/suculent/thinx-device-api

## Forensic Information

**Operating System:** the operating system you observed the issue on.

Ubuntu

**Environment Information:** information about your project's environment, see instructions below:

Node.js 8.1.4; nyc 10.3.2, 11.0.0, latest

https://gist.github.com/suculent/31cb9bfc6c7d5937c5a23d6ccb494cb0

**Comment by ScottFreeCode** [comment]
I was using Node 8.1.0 on Mac with whichever version of NPM is bundled with it (I think it's 5.0.3?), used `npm i nyc@latest` to upgrade from the last 10.x.y version, and got this issue; based on the find-up issue I tried `npm ls` and found a lot of invalid, extraneous and missing packages; tried `npm prune` and `npm i` and couldn't fix it; ended up `rm -r -f node_modules && npm i` to make it work right. If I have time at some point I'll see if I can put together a series of instructions to reliably reproduce the issue, and we can file it with NPM, if it isn't already fixed in `>= 5.1.0`.

**Comment by bcoe** [comment]
@ScottFreeCode this is an issue with specific versions of npm hoisting the wrong deep dependency to the top. It should be fixed for you in the near future, with upcoming npm CLI bug fixes.

**Comment by camsjams** [comment]
Doing `rm -r -f node_modules && npm i` works, glad I didn't have to downgrade to < Node 8, thanks @ScottFreeCode
