### ISSUE TITLE
nyc v11.1.0 not published

### ISSUE THREAD

**Issue by sudo-suhas** [istanbuljs/nyc#634]
The latest version of `nyc` published on npm is still `v11.0.3` which was released 3 weeks ago.
`v11.1.0` [was released](https://github.com/istanbuljs/nyc/commit/a3f033f597624d09d28ba3b15eadb6fb5fdab9a2) 2 days ago. Perhaps forgot to do `npm publish`?

**Comment by EvgenyOrekhov** [comment]
Looks like `v11.1.0` have been published for a short period of time, because somehow I managed to update nyc to it, but now npm says

```text
Package  Current  Wanted  Latest
nyc       11.1.0  11.1.0  11.0.3
```

**Comment by bcoe** [comment]
@EvgenyOrekhov @sudo-suhas `11.1.0` will be the next release of nyc, I was waiting for feedback from a few users before we release it:

```bash
 npm dist-tag ls nyc
latest: 11.0.3
next: 11.1.0
```

You can try out this version and give feedback by running, `npm i nyc@next`.

**Comment by sudo-suhas** [comment]
Thanks @bcoe.

**Comment by ScottFreeCode** [comment]
For what it's worth (and just to put in my experience that led me to this issue report), having a version published to NPM with a version higher than the one tagged `latest` can do weird things to `npm outdated` -- right now, for instance, if you `npm i nyc@latest && npm outdated` you are likely to get a red `nyc` in the output (I believe because NPM sets the wanted version to `^11.0.3`, which includes `11.1.0`), but if you `npm i nyc@next && npm outdated` you will get a yellow `nyc` in the output because you have the newest wanted version but not the one tagged `latest`. Depending on the exact use case, it can be worth considering [pre-release tags](https://docs.npmjs.com/misc/semver#prerelease-tags) as an alternative strategy for experimental and/or release-candidate publications -- whatever makes the intention clearest, of course. 😸

**Comment by bcoe** [comment]
@ScottFreeCode might be worth opening an issue on npm/npm; I've noticed this behavior too, and it's probably a pretty simple patch -- I've honestly just always ignored the behavior.
