### ISSUE TITLE
Is it possible to use nyc to get code coverage of protractor e2e tests

### ISSUE THREAD

**Issue by dinukadesilva** [istanbuljs/nyc#676]
I mean, Is it possible to instrument client-side javascript files and get their coverage from protractor test scripts.

**Comment by sarawut-p** [comment]
I want to know it too.

**Comment by stoffeastrom** [comment]
I haven't done it myself yet for protractor but for browser testing. It should be pretty much the same though. Some pointer on how to achieve this would be

* You need a web server with middleware that instruments the source files serve to the browser. You can get the instrumenter by `const instrumenter = nyc.instrumenter();` and the `instrumenter.instrumentSync()`
* You need a browser runner that can emit the coverage back to the web server
* On the web server side you need to populate the coverage object into global e.g `global.__coverage__`
* Call `nyc.writeCoverageFile()`
* Call `nyc.report()`

Hopte this get you going...

**Comment by bcoe** [comment]
@dinukadesilva I commend taking a look at the approach used in @mikeal's project cappadonna:

If you pre-instrument your files, and then output the `window.__coverage__` variable, you can then use nyc to report.

This approach can be found here:

https://github.com/mikeal/cappadonna/blob/master/index.js#L19

feel free to reopen this issue if you run into any problems.

**Comment by russoturisto** [comment]
Just added this to slack:

Hi, I'm trying to manually instrument a bundle file that has separate .js.map file.   I run nyc instrument and replace the original bundle file with the instrumented one.   Then I run my tests in browser, save window.__coverage__ and report on it.  But the generated html report shows only coverage on the instrumented source, not the files from the source maps.  What am I doing wrong:

nyc instrument main.bundle.js main --source-map --exclude-after-remap=false
// copy the file, run the interactive tests, save the coverage json
nyc report --reporter=html --exclude-after-remap=false

Thanks, :)

PS:  I can't run nyc programmatically or as part of a test suite because protractor doesn't support it

would I get better results if I instrumented files right in the browser?


in that case, how do I add istanbul/nyc source to my app?

**Comment by russoturisto** [comment]
A follow up on my previous post: I was able to get coverage reports on the original bundle file, but not on the source via .js.map files.  This is good enough for us right now because we lazy load almost every feature and the generated dev bundle is readable enough to map it back to the TypeScript source.
Thanks, :)

**Comment by bcoe** [comment]
@russoturisto great, I'm glad you found a workaround. @thegecko perhaps you could provide @russoturisto some direction; it sounds like his workflow is somewhat similar to what you're doing with pre-instrumenting files.

A complete aside, but could I convince either of you to write a tutorial for https://istanbul.js.org/, that talks about the process of pre-instrumenting source-files with source-maps? (this isn't something I know much about, but is certainly something that folks in the Istanbul community see to need).

**Comment by russoturisto** [comment]
Yep, I could do that once I figure out TS to JS source mapping coverage results, but I have to table that for now since I already spent too much time on in, probably will figure it out sometime next year. :)

**Comment by russoturisto** [comment]
I never got around to actually making TypeScript mappings to work but we did end up doing just that.  We deployed instrumented code and then sent the coverage object back to the server for processing.  But this was of limited to value to us since the generated report was on JavaScript, not on our initial TypeScript source.

**Comment by trajano** [comment]
@tkssharma I tried to do it but it didn't work, but I am using Ionic.  Here are the key lines in my `package.json` and this didn't create the `global.__coverage__`  variable when I am trying to use the console.

    "ionic:serve": "ionic-app-scripts serve",
    "e2e:serve": "nyc --instrument npm run ionic:serve",

**Comment by ericminio** [comment]
Hi
In case it is usefull for somebody else, I went through this recently with classic js frontend hosted on GitHub pages, using mocha and jsdom: https://github.com/ericminio/tdd

Same idea: instrument, run the test, drop the coverage info in `nyc_output`folder, then report.
Note the file `4.format-time.spec.js`which explores a different approach.

Cheers
