### ISSUE TITLE
Consider restoring older node support

### ISSUE THREAD

**Issue by ljharb** [istanbuljs/nyc#682]
I have a lot of modules that are locked at nyc v10, because v11 [drops support for older versions of node](https://github.com/istanbuljs/nyc/blob/master/CHANGELOG.md#breaking-changes).

I find that making sure my modules work on as many versions of node as possible helps ensure that people who are stuck on those node versions (for whatever reason) have fewer variables when upgrading - in other words, the smoothest upgrade is when you can upgrade all your deps first, ship that, and then upgrade your platform, and ship that - when you have to upgrade both at once, platform updates are much riskier, so it's much less likely to happen.

Based on that rationale, I have a lot of modules that feature-detect things and have slightly different code paths in older engines (older node versions being a useful proxy for older browsers, as well).

Running coverage only in node 4+ can't ever give me 100% coverage in these modules, even if I *do*, conceptually, have 100% coverage. I'd like to combine my coverage reports across older versions of node also, so that I can ensure I do, in fact, have 100% coverage.

It would be ideal if nyc would be willing to restore support for older nodes (and be willing to PR or replace any deps that need it) - I'd be happy to help in that effort if so.

**Comment by bcoe** [comment]
@ljharb unfortunately far too many of nyc's dependencies require Node 4+, which was our motivation for dropping `0.10` support. We've been running on 4+ for several months now, and I don't plan on going back on this decision.

Perhaps you could pin to an older version of nyc for some of your dependencies that still require testing on 0.10?

**Comment by ljharb** [comment]
That's unfortunate. If I pursued updating all those dependencies, such that a single PR was necessary to restore support in nyc, would you be willing to accept it?

(100% of my dependencies require testing on 0.6 even, so basically that means I have to pin to v10 forever on everything)

**Comment by bcoe** [comment]
@ljharb I'd accept a pull request against a `0.10` branch if you feel like maintaining it and would publish to a `node10` tag under the `nyc` name -- so that you'd be able to install using `nyc@node10`.

I wouldn't accept a pull to the main branch... I also dragged my feet dropping `0.10` support, but gradually I realized the writing was on the wall and too many dependencies of dependencies started introducing newer JavaScript syntax. It became impossible to upgrade to the latest versions of libraries, and in general made maintaining nyc and yargs a pain in the butt.
