### ISSUE TITLE
NYC not producing reports in some machines

### ISSUE THREAD

**Issue by andre-l-mm** [istanbuljs/nyc#717]
I am trying to use nyc with mocha to generate coverage reports but it does not work in some machines while it works perfectly in others. 

## Expected Behavior
nyc should generate reports according to parameters provided in the command line. Example below: 

nyc --reporter=cobertura --reporter=html --reporter=text mocha --recursive --require test/helpers/chai.js

## Observed Behavior
The above works as expected in a mac computer but it fails in some of our windows laptops and it is also failing in our windows build server. 

We have observed the folder .nyc_output is empty after executing the command in the machines in which the problem happens. 

We also noticed that the mocha tests are executed fine as we can see in the console log, only the reports are not produced. 

## Bonus Points! Code (or Repository) that Reproduces Issue
Unfortunately, this code is in a private enterprise git repo and I am not allowed to share it. The command output looks like below. Note the invalid coverage report at the end: 

[nyc_output.txt](https://github.com/istanbuljs/nyc/files/1455492/nyc_output.txt)

## Forensic Information

**Operating System: Windows Server 2012 R2
**Environment Information:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt
Output below:
[output.txt](https://github.com/istanbuljs/nyc/files/1455499/output.txt)

**Comment by andre-l-mm** [comment]
Hello, Would anyone have any tips on this issue?

**Comment by bcoe** [comment]
@andre-l-mm hello 👋 we do run tests running on AppVeyor (which is Windows Server I believe) and I do occasionally boot a VM and test.

To be able to output coverage reports, nyc hooks the exit event of the Node process; my guess would be that on windows this isn't firing for you. One thing I noticed from your output, is that one of your modules relies on `exit-hook` (at a glance I wonder if this is interfering with the exit event on Windows).

For starters, I'd try creating a small testing repo with nyc/mocha and run this (rather than running your full application); I'm curious to see if it's a specific dependency in your project that's causing issues, or perhaps general flakiness with Windows.

Sorry for the slow reply, supporting Windows is definitely something we care about.

**Comment by andre-l-mm** [comment]
@bcoe Thanks for your response. I am out of the office today and tomorrow but will try what you suggested on Wednesday and let you know.

**Comment by andre-l-mm** [comment]
@bcoe Apologies for the delay. I tried what you mentioned but still get the same issue. Attached you can see a very simple code with 2 tests only. It has no dependencies other than the dev dependencies we use to write unit tests (chai, sinon, rewire). It runs the tests but still does not produce the coverage report on windows. It works fine on Mac. 

[nyc-test.zip](https://github.com/istanbuljs/nyc/files/1522291/nyc-test.zip)

**Comment by benedictchen** [comment]
For me, not even producing reports on mac :-(

**Comment by bcoe** [comment]
@benedictchen I suggest opening a new issue with more details. nyc definitely isn't broken for most folks, so there's probably an environment specific issue causing you both trouble. you can also join this chat:

http://devtoolscommunity.herokuapp.com/

For real-time help from folks in the community.
