### ISSUE TITLE
Running nyc does not write text-lcov reports into report-dir

### ISSUE THREAD

**Issue by StickyCube** [istanbuljs/nyc#744]
running `nyc --reporter=text-lcov ...` outputs the report to stdout but does not write the file into the report-dir. It does write the files when using the html reporter.

## Expected Behavior
The report should be written to report-dir regardless of the reporter

## Observed Behavior
The report is only written if the reporter is html

## Bonus Points! Code (or Repository) that Reproduces Issue
[See here](https://gist.github.com/StickyCube/45ea4e92d24c5b7a3a852c5e627c5613)

## Forensic Information

**Operating System:** 
Windows x64

**Environment Information:**
node: 8.9.1
npm: 5.5.1

**Comment by bcoe** [comment]
@StickyCube try using the `lcov` report rather than the `lcov-text`; `lcov-text` purposefully only outputs text (as an alternative to `lcov` which writes the report to disk). The idea was that `lcov-text` could be used for the purposes of piping the output directly to a service like coveralls, vs., `lcov` which places a file on disk which you can work with.

**Comment by AnanyaJha** [comment]
I have a typescript project running in vscode and I'm using the `lcov` option and not seeing an `.nyc_output` folder being generated or a `coverage` folder being generation with the `lcov.info` file
