### ISSUE TITLE
/* istanbul ignore next */ ignored with ES6 syntax ?

### ISSUE THREAD

**Issue by jy95** [istanbuljs/nyc#769]
## Expected Behavior

I expected that [excluded comments](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) work to keep my coverage with my ES6 syntax.

## Observed Behavior

Simply ignored ^^

## Bonus Points! Code (or Repository) that Reproduces Issue

- My [repository](https://github.com/jy95/torrent-files-library/)
- [Main File](https://coveralls.io/builds/15252248/source?filename=src%2FTorrentLibrary.js) on coveralls.io

**Comment by targumon** [comment]
@jy95 I think I'm facing this too. Did you find a workaround?

**Comment by jy95** [comment]
No : I guess the coverage stuff doesn't like this excluded comment in the 'catch' part of my code ^^

**Comment by JaKXz** [comment]
Sorry for the late reply - is this still an issue with the latest nyc?

**Comment by jy95** [comment]
Test by yourself : try to make a PR on my repo with the latest nyc

**Comment by coreyfarrell** [comment]
@jy95 the babelrc in your repo sets `comments: false`.  Please try enabling comments for your test environment.  I suspect that babel is stripping these comments before istanbul can see them.

**Comment by coreyfarrell** [comment]
@jy95 I just tested your current repo by adding the following code inside src/TorrentLibrary.js:
```js
    /* istanbul ignore next */
    if (false) {
      console.log('here');
    }
```

This unreachable `console.log` was not reported, I then removed the `istanbul ignore next` and it was reported.  Your repo shows 100% coverage so I'm closing this issue as it appears to be resolved (turns out I was wrong about `comments: false` causing an issue).
