### ISSUE TITLE
Files without extension not covered

### ISSUE THREAD

**Issue by aalexgabi** [istanbuljs/nyc#781]
## Expected Behavior
To have coverage for bin/service. When I run: 
```
root@99d688591709:/opt/carbon/nyc-test-project# nyc --all -r html -r json bin/service 
init
this file is used
run
```
Or:
```
root@99d688591709:/opt/carbon/nyc-test-project# nyc -n bin/service --all -r html -r json bin/service 
nyc [command] [options]
nyc [options] [bin-to-instrument]

Commands:
  nyc check-coverage               check whether coverage is within thresholds
                                   provided
  nyc instrument <input> [output]  instruments a file or a directory tree and
                                   writes the instrumented code to the desired
...
```
Or:
```
root@99d688591709:/opt/carbon/nyc-test-project# nyc -n './bin/service' --all -r html -r json bin/service 
init
this file is used
run
```

## Observed Behavior
File bin/service is not included in coverage report.
## Bonus Points! Code (or Repository) that Reproduces Issue
https://mega.nz/#!xAIyEKRD!0rvehlygRkcuW-vQJMe_1tf4WhTxhwWPyz2aN_P19_g
## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

```
root@99d688591709:/opt/carbon/nyc-test-project# node --version
v8.9.2
root@99d688591709:/opt/carbon/nyc-test-project# npm --version 
5.5.1
root@99d688591709:/opt/carbon/nyc-test-project# npm ls
/opt/carbon/nyc-test-project
`-- (empty)

root@99d688591709:/opt/carbon/nyc-test-project# l       
```

**Comment by bcoe** [comment]
@aalexgabi nyc requires the file-extension hint when deciding how to process files; it registers a loader on a specific file extension.

I recommend renaming `bin/service` to `bin/service.js`. If you add `service.js` to the `bin` stanza in your package.json, you can still link it globally as `service` on your system, and it's good practice to have a file extension.

**Comment by shellscape** [comment]
@bcoe since the practice of extension-less, executable files (with leading shebang) is common, it would seem that this is indeed a shortcoming of `nyc`, rather than some whacky thing us whacky users are doing. 

> and it's good practice to have a file extension.

Not debating your stance, but it's _highly subjective_ and one can find any number of files without extensions that ship with an OS (even on Windows systems).

Count me as disappointed this wasn't treated as a "real issue." nyc isn't stated to be an opinionated module anywhere, so it's surprising that it would be opinionated on how files were named. It would seem that allowing configuration for which loader to use with which files, or perhaps even inspection for a shebang, would have been a much more flexible solution.

**Comment by aalexgabi** [comment]
Istanbul worked with files without extensions if you included them explicitly.

If it's worth anything: the only reason we switched from istanbul to nyc is because we started using async/await. I did not have as many issues with istanbul as with nyc.

I keep my stance on considering this a bug: I tell nyc to include my file and it does not include it.

As for the typescript part there are number of possible solutions:
* use a specific syntax. For example something like: `-n 'bin/service|ts'`
* have different include flag `--ts-include bin/service`
* detect typescript files based on the typescript shebang (i don't know if it even has one)
