### ISSUE TITLE
nyc does not check coverage from given file

### ISSUE THREAD

**Issue by aalexgabi** [istanbuljs/nyc#783]
## Expected Behavior
```
nyc check-coverage --statements 90 test/coverage/coverage-final.json
```
Should check coverage compared to test/coverage/coverage-final.json
## Observed Behavior
It checks coverage compared to .nyc_output folder

Because I use async class methods I can't use istanbul but when I need to check coverage I have to use istanbul check-coverage due to limitations of `nyc check-coverage`:
```
istanbul check-coverage --statements 90 test/coverage/coverage-final.json
```

## Forensic Information

**Operating System:** Manjaro

```
node v8.9.2
npm 5.5.1
```

**Comment by JaKXz** [comment]
Hi @aalexgabi sorry for the late reply - I think if you specify `--temp-dir test/coverage/` with the appropriate .json files in that folder this should work! Let me know if not.

**Comment by coreyfarrell** [comment]
That is correct, `--temp-dir test/coverage` will work.  An issue that remains is `nyc check-coverage --help` does not list this as a valid flag, so I think this is a documentation issue.

**Comment by JaKXz** [comment]
@coreyfarrell I think we can just close this issue since the question has been answered and the `--temp-dir` option is documented by `npx nyc --help`. There's also a [FAQ link](https://github.com/istanbuljs/nyc/issues?utf8=%E2%9C%93&q=label%3Aquestion+) on the istanbulj.js.org website that links to all question-issues whether they're open or closed :)
