### ISSUE TITLE
Exclude mocha global beforeEach in coverage calculation?

### ISSUE THREAD

**Issue by svenlombaert** [istanbuljs/nyc#807]
Hi,

I was playing around in a typescript project witch nyc, and everything works great actually.
We're using sequelize, and I have a beforeEach hook that calls `.destroy()` on all models (so I'm importing every model definition file in that hook). Because of this hook, nyc reports that my models are 100% covered, which is actually not true at all.

I tried just doing `sequelize.db.sync({force: true})` instead of calling destroy on every model, but this makes my tests way way slower. (since that does a DROP table/CREATE table, instead of truncating all the tables)

Any way I could exclude the hook from the calculation (or maybe another tip for truncating my tables with sequelize)?

Thanks

**Comment by JaKXz** [comment]
Hi @svenlombaert sorry for the late reply! This is a very interesting question. I'm going to ping @boneskull and @bcoe just to see if they have anything to add, because I'm not sure where to start. My first thought is that this sounds like something that is outside of nyc's responsibilities, but that's a shot in the dark at best.

> I was playing around in a typescript project witch nyc, and everything works great actually.

This is awesome though! Would love to see a your repo anyway :)

**Comment by boneskull** [comment]
without seeing the code I don’t think we can be of much more help. not a mocha issue

**Comment by svenlombaert** [comment]
You’re correct that it’s probably out of scope 😅. Just wondering if there was a way to maybe exclude certain files from the coverage report. It comes across as an anti-pattern but could come in handy in cases like this.

**Comment by coreyfarrell** [comment]
This is out of scope for nyc (I believe impossible to directly support).  It is impossible for us to suppress coverage based on what code is calling the covered functions.  So if `model.delete()` reports coverage, it does so without knowledge of being called from `beforeEach` or not.  You can't make that function collect coverage when run by tests but ignore calls from `beforeEach`.

One (untested) possibility would be to make `beforeEach` run a separate script in a new process that would:
1. Import the model
2. Run model.delete()
3. Set `__coverage__ = {}` to clear all coverage from the script's process (because the script is still running indirectly under nyc).
4. Exit with success allowing the mocha process to continue.

This separate process would allow you to completely clear the data collected by that process.

**Comment by JaKXz** [comment]
Closing as out of scope.
