### ISSUE TITLE
Feature Request - allow pass env-vars to the SUT

### ISSUE THREAD

**Issue by osher** [istanbuljs/nyc#878]
I would like to be able to instruct `nyc` to pass environment variables to it's sub-processes so I would not need one more wrap in form of more cli context libraries such as 
- https://www.npmjs.com/package/env-pass
- https://www.npmjs.com/package/cross-env

**Comment by JaKXz** [comment]
Hi @osher sorry for the late reply - while I appreciate you filing this issue, I think it is outside the scope of nyc, unless, you're willing to see it through with a PR and appropriate tests :) or if there's strong enough of a response from the community. Since this has been stale for a while I am going to close it for now.
