### ISSUE TITLE
-a flag and `all: true` are ignored in v13.0.0

### ISSUE THREAD

**Issue by ajb3ck** [istanbuljs/nyc#887]
## Expected Behavior
When running nyc with `all: true` in the nyc configuration all files should be included in coverage

This issue appears if `all: true` is removed from the package.json config and the -a flag is used in the npm test script.

## Observed Behavior
Only tested files are included

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/ajb3ck/nyc-test

## Forensic Information

**Operating System:**  macOS High Sierra
**Environment Information:** https://gist.github.com/ajb3ck/4c1a1147df03c9633ec798ed26bb5a1d
**nyc version:** 13.0.0
**npm test script:** cross-env NODE_ENV=test nyc mocha
**nyc config in package.json:**
```
"nyc": {
    "include": [
      "src/**/*.js"
    ],
    "require": [
      "babel-register"
    ],
    "reporter": [
      "text",
      "lcov"
    ],
    "all": true,
    "sourceMap": false,
    "instrument": false
  }
```

**Comment by coreyfarrell** [comment]
It appears this issue is due to mixing of babel 6 and babel 7.  Your repository is using babel 6 (and babel-plugin-istanbul@4).  NYC uses babel 7.  I was able to get your repository working by upgrading babel dependencies to v7 and upgrading babel-plugin-istanbul to v5.  So I'd recommend sticking with nyc 12 until you are ready to upgradfe to babel 7.

**Comment by JaKXz** [comment]
Thanks for the issue @ajb3ck. Since we haven't heard back I'm going to close this issue for now, but feel free to reopen it once you've tried Corey's suggestion.
