### ISSUE TITLE
nyc ignores report-config

### ISSUE THREAD

**Issue by FabioIngrao** [istanbuljs/nyc#907]
## Expected Behavior
specifying in package.json
"nyc" : {
  report-config: {
    html: {
      // options for html reporter
    }
  }
}

is supposed to provide the specified options to the reporter.
However, the nyc code does not read the "report-config", and doesn't add them to the options passed to the reporter.

**Comment by JaKXz** [comment]
@FabioIngrao sorry for the late reply. This sounds like an interesting suggestion, since this is not currently supported in `istanbuljs`. If you are willing to provide more information or a PR(s) with your design proposal, that would be great! You will probably want to start in the istanbuljs monorepo so that the reporting library underneath understands the options you want to pass to it to customize the report.
