### ISSUE TITLE
Coverage not working for files outside working directory

### ISSUE THREAD

**Issue by sampathkumarm** [istanbuljs/nyc#962]
I am unable to run coverage on the spec files outside the root directory (where package.json resides). Please find the screenshot attached and let me know if i am doing anything wrong here. Why the relative path doesn't work?

NYC should be able to run coverage on files using relative paths too.

## Observed Behavior
![coverage issue](https://user-images.githubusercontent.com/6489309/50821685-a44f1380-12e4-11e9-8c53-5bba76de3cc0.PNG)
![result](https://user-images.githubusercontent.com/6489309/50821692-aa44f480-12e4-11e9-8649-211c3eb25e4b.PNG)

## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node 8.9.4; npm 5.6.0; npm ls' > output.txt

2. share a gist with the contents of output.txt.

**Comment by JaKXz** [comment]
@sampathkumarm sorry for the late reply! Can you please provide a minimal reproduction repo with the latest version of nyc? Have you set your `include` array to look in your relative path? [As documented](https://github.com/istanbuljs/nyc#selecting-files-for-coverage) nyc looks in your cwd by default unless told otherwise.
